### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by jonathanbridges** [jonathanbridges/click-camp#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by jonathanbridges** [comment]
@minucos Auth User MVP ready for review.

Thanks!

**Comment by minucos** [comment]
Realise this was still open! Completed and closed
